---
- name: Configure nginx web server
  hosts: webserver
  remote_user: ubuntu
  become: yes
  tasks:
  - name: uninstall nginx server 
    apt: 
      name: nginx
      state: absent
  - name : stop nginx server
    service: 
      name: nginx
      state: stopped