---
- name: Wait for ssh connection
  hosts: aws_ec2    #all
  gather_facts: False
  tasks:
    - name: Ensure ssh port open 
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3.9


- name: Install Docker and Docker-compose
  hosts: all
  become: yes
  # gather_facts: False
  tasks: 
    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        update_cache: yes
        state: present
        # use_backend: yum
    - name: Install Docker-compose
      ansible.builtin.get_url: 
        url: https://github.com/docker/compose/releases/download/2.19.0/docker-compose-Linux-x86_64'
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Install docker python module
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose


- name: Add ec2-user to docker group
  hosts: aws_ec2    #all
  become: yes
  tasks: 
    - name: Add ec2-user to docker group
      ansible.builtin.user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      ansible.builtin.meta: reset_connection


- name: Start docker containers
  hosts: aws_ec2    #all
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: /home/ziad/projects/java-mysql-app/docker-compose-full.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      community.docker.docker_login: 
        registry_url: https://index.docker.io/v1/
        username: ziadmali
        password: "{{docker_password}}"
    - name: Start container from compose
      community.docker.docker_compose: 
        project_src: /home/ec2-user
        state: present
